name: Deploy Tailwind Site to GitHub Pages

on:
  push:
    branches: [main]  # Ana branch adınız (main veya master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build  # package.json'daki build komutunuzu çalıştırır
      
    # Jekyll'i devre dışı bırakmak için kritik adım
    - name: Disable Jekyll
      run: |
        touch ./dist/.nojekyll
        echo "Jekyll disabled" > ./dist/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Build çıktı klasörünüz